name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION_STRING}}
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "outoflensapi"
          heroku_email: "felipebeserra25@gmail.com"
          usedocker: true